# Generated by Django 5.0.6 on 2024-07-15 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_apikey_credits_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='youtube_upload_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='YouTubeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('analysis_result', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
