# Generated by Django 5.0.6 on 2024-07-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_uploadhistory_youtube_upload_count_youtubeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicallhistory',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apicallhistory',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
